Repository understanding-search/maze-dataset, pull requests merged in 2024-07, with the labels that each got.

#43 Fix generation meta collection
  maze_dataset/dataset/dataset.py
  maze_dataset/dataset/maze_dataset.py
  poetry.lock
  pyproject.toml
  tests/unit/maze_dataset/processing/test_collect_gen_metadata.py
Labels: bug, code-quality

#37 Tokenizer Overhaul Step 2
  .github/workflows/checks.yml
  .gitignore
  README.md
  makefile
  maze_dataset/__init__.py
  maze_dataset/constants.py
  maze_dataset/dataset/dataset.py
  maze_dataset/dataset/maze_dataset.py
  maze_dataset/generation/__init__.py
  maze_dataset/generation/generators.py
  maze_dataset/maze/lattice_maze.py
  maze_dataset/plotting/print_tokens.py
  maze_dataset/testing_utils.py
  maze_dataset/token_utils.py
  maze_dataset/tokenization/__init__.py
  maze_dataset/tokenization/all_tokenizers.py
  maze_dataset/tokenization/maze_tokenizer.py
  maze_dataset/tokenization/save_hashes.py
  maze_dataset/tokenization/token_utils.py
  maze_dataset/tokenization/util.py
  maze_dataset/utils.py
  notebooks/demo_mazetokenizermodular.ipynb
  notebooks/demo_new_tokenizers.ipynb
  notebooks/demo_tokenization.ipynb
  notebooks/profile_dataset_save_read.ipynb
  poetry.lock
  pyproject.toml
  tests/all_tokenizers/test_all_tokenizers.py
  tests/unit/maze_dataset/generation/test_coord_str_tuple.py
  tests/unit/maze_dataset/generation/test_maze_dataset.py
  tests/unit/maze_dataset/generation/test_solved_maze.py
  tests/unit/maze_dataset/tokenization/test_coords_string_split.py
  tests/unit/maze_dataset/tokenization/test_maze_tokenization.py
  tests/unit/maze_dataset/tokenization/test_token_utils.py
  tests/unit/maze_dataset/tokenization/test_tokenizer.py
  tests/unit/maze_dataset/tokenization/test_util.py
  tests/unit/maze_dataset/tokenization/test_vocab.py
Labels: enhancement, tokenization

#36 Fix save/load profiling notebook and test
  maze_dataset/dataset/dataset.py
  maze_dataset/dataset/maze_dataset.py
  notebooks/profile_dataset_save_read.ipynb
  tests/unit/maze_dataset/generation/test_maze_dataset.py
Labels: bug
